### ISSUE TITLE
[Quest][Horde] Triage

### ISSUE THREAD

**Issue by Konnla** [FeenixServerProject/Archangel_2.4.3_Bugtracker#1904]
I have level 225 First Aid, the only way at this point to progress past this level in First Aid is to do the quest " http://www.wowhead.com/quest=6622 " (Triage). The NPS appears to be there, but nothing in game registers for him actually being there. I can't target him and nothing shows up when I scroll over him with my Mouse. Obviously this doesn't allow me, and possibly others to continue the quest, and progress in First Aid. 

The NPC is here " http://www.wowhead.com/npc=12920 " (Doctor Gregory Victor)
His location is Hammerfall in Arathi Highlands.
My Character Name is Kaizen (Blood Elf Rogue)

**Comment by Caspa0** [comment]
NPC is completely un-interractable to me. He shows a yellow exclamation mark to show he has a quest but I cannot see his name nor target him in any way. Previous comments suggest that this happens if you have an open quest with him however I have no quests in my quest log whatsoever.

I have attempted re-logging.
I have attempted loading no addons.
I have attempted deleting the WTF folder.
I then attempted to pick up the quest to speak with him from the Orgrimmar First-Aid trainer and he now has a yellow question mark over his head but is still not interractable.

As seen here:
![image](https://cloud.githubusercontent.com/assets/16357148/12708956/ad18b8e2-c8e9-11e5-93c6-9b4bd4dd8325.png)

And this is what a normal interractable NPC looks like:
![image](https://cloud.githubusercontent.com/assets/16357148/12708975/f245bcb2-c8e9-11e5-8811-a20ba9bf9733.png)

**Comment by Caspa0** [comment]
I have checked him every day and he was still not interractable until today. I am now level 70 and he now works fine, there was a server issue about an hour ago and possibly it was restarted which may have fixed it.

**Comment by Nzzoth** [comment]
Sounds interesting, incase it happens again drop a comment and thank you for your report.

**Comment by devastator** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/3583
