### ISSUE TITLE
[GENERAL][CRUCIAL!] Interrupted

### ISSUE THREAD

**Issue by warlee** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3104]
Current situation: When you try to cast any spell( ex. Ice Block, Blink, any spell that is affected by a gloobal cooldown) you get sometimes message 'interrupted'. I cant reproduce it always but when you 'press' spell, you get gloobal cooldown but nothing happens, while you spam the button you get a message 'spell is not ready yet' from the gloobal cooldown of the spell that you never casted. 

You can see it vividly in the video:
http://youtu.be/TCYc580DFj0

Desired situation: You should get gloobal cooldown only if you cast the spell. You shouldnt get message 'interrupted' at all. Same thing has happend on warsong server afaik after the core merge.

**Comment by Forcy** [comment]
Create Undead Mage

.levelup 69
.learn 27082

You need to have "Default" Key Binds in game.
Cast Arcane Explosion and at the same time use "W or "S" to move forward/backwards (It might take couple of attempts till correctly reproduced)

Here is an old video that I've found, it is the same issue just relating strafing left and right instead of moving back and forth

http://www.youtube.com/watch?feature=player_embedded&v=NPgHAfBETrs

**Comment by warlee** [comment]
Issue still exists

**Comment by Nzzoth** [comment]
Incase someone encounters this please comment.

Issue closed.
