### ISSUE TITLE
Nether Vortex should be no longer BoP

### ISSUE THREAD

**Issue by ladnopivo** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3528]
from patch notes:
Patch 2.4.0 (25-Mar-2008): You can now buy Nether Vortex from G'eras for 78 Badge of justice. They also are no longer BoP.

source: http://www.wowwiki.com/Nether_Vortex

**Comment by Lederi** [comment]
The server is on Content Patch Patch 2.1.0  (BT+MH) or pre Patch 2.3.0 (ZA)

**Comment by smspf** [comment]
it says in the server name 2.4.3, and there are several things proving this, but off the top of my head i know grimtotem spirit guides arent tameable on here, which means, if the server were as blizzlike as possible, it has on patch 2.3.2 at the very latest, as they were tameable in every patch before this
so if they're on 2.1.0 they should make them tameable 
i guess i'm just ranting because i want a ghost wolf and almost all the other unique pets dont work on feenix, either way it's not blizzlike for them to not be tameable beasts on content patch 2.1.0 plz fix

**Comment by Forcy** [comment]
We will change that with the release of ZA, closing for now.
