### ISSUE TITLE
[Warrior] Flurry

### ISSUE THREAD

**Issue by Vinxhe** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3558]
From the original 2.4.0 changelog:
Flurry will properly refresh if a crit occurs with 1 charge left. 

This bug is currently still in the game on Archangel.

source: http://www.wowwiki.com/Patch_2.4.0

**Comment by teddys** [comment]
How to reproduce:
You need 2 clients, on one create an orc warrior
.levelup 70
.spec 5/5 flurry
.t test
On the other one create a draenei priest
.levelup 70
.mod hp 1000000000
.t test
Start attacking the priest and observe flurry buff behaviour.

video evidence : https://www.youtube.com/watch?v=YI7Heqd7WUA

current situation : If you have 1 charge of flurry and you crit, flurry disappears instead of refreshing itself to 3 charges

expected : If you crit when you have 1/3 charges of flurry, flurry is refreshed to 3/3.

**Comment by Nzzoth** [comment]
Can't reproduce on both PTR or PLTR, if this is still the case someone leave a comment and I will reopen the issue.
