### ISSUE TITLE
[Crash] Upon entering Theramore

### ISSUE THREAD

**Issue by Edupop** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3573]
Client throws an ACCESS_VIOLATION exception upon loading into Theramore from the Alliance mage teleport spell. 
Reloading the client, deleting the cache, or disabling addons has no effect. 

WowError output: http://pastebin.com/m3jHs1HG

As no input is accepted from the player before crashing, characters are effectively stuck.
(EDIT: Website unstuck works)

I'll try to test the range of the crash on another character.

**Comment by Edupop** [comment]
Seems to be restricted to an area south of the tower, possibly due to the weather effect caused by the Tethyr event?

**Comment by Nzzoth** [comment]
Hello Edupop,

It might be, this is a question for a developer therefor I can't give you an answer. This issue was ongoing for some time now, the problem is it's hard to reproduce and get the cause. Could you include your character name (only character not the account!) and the exact time when this happen aswell please?

Kind regards, Nzzoth.

**Comment by Edupop** [comment]
Character name Preaty for the mage. I was able to replicate it on my paladin Hashbringer by simply riding into Theramore isle from the gate and around to the backside of the tower. As for exact times, see the respective posts above.

**Comment by Edupop** [comment]
Unstuck my mage and tried flying this time from Feralas and crashed again. Seems consistent on my end.

**Comment by lajhar** [comment]
It's not an issue anymore /close
