### ISSUE TITLE
Hunter global cooldown 1.5s when it should be 1.0

### ISSUE THREAD

**Issue by kauski** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3670]
Hunter Global cooldown currently is 1.5 seconds, when it should be 1.0 seconds.

Huge problem for dpsers, we have to go with low dps steady - auto rotation, when fixin that global cooldown bug allows to do 3:2 rotation, wich is insignificantly higher dps than the 1:1 wich we are forced to go now.

I believe this is high issue for hunter dps along with pet dmg being too low.

**Comment by Blaqwar** [comment]
This will get looked at sooner if you can provide some kind of proof.

**Comment by kauski** [comment]
http://wow.gamepedia.com/Cooldown

also http://wow.gamepedia.com/Patch_2.4.0

"spell haste reduces global cooldown on all expect melee & ranged attacks"

as being said, melee and ranged attacks should have that 1.0 sec cooldown

**Comment by kauski** [comment]
+how else you were supposed to do the legendary 3:2 rotation, if you should shoot allways autoshot if its less than 0,5 seconds away from firing it.

if global cdr is 1.5 sec, with badge crossbow and ~80 haste you should be standin at 1.9 sec autoshot timer.

so theres noway that you could pull 2 steady shots between autoshot ever with 1.5 sec cdr. if ur supposed to do autoshot allways when is less than 0,5 sec from fired.

**Comment by Blaqwar** [comment]
From your own link to Gamepedia (from the official patch notes): "Spell Haste: Spell haste now reduces the global cooldown on spells, down to a minimum of 1 second. This change does not apply to melee and ranged abilities."

Also as far as I understand it the 3:2 rotation isn't possible on Feenix because of how auto shot works differently. Instead of having a delay like on live (the delay made it possible to fit another SS in) it fires instantly. I haven't been able to find any evidence that the Hunters had any GCD changes in 2.4.3

**Comment by kauski** [comment]
"The base global cooldown is generally 1.5 seconds for all classes except hunters, rogues" copypasted from first link i gave.

ofc you dont find any patch notes in 2.4.3 because it was in game at like vanilla, so why it would be in 2.4.3 notes if it was applied way before?

**Comment by Blaqwar** [comment]
I got my shovel and dug through some old stuff just for you. Turns out Hunters got a 1 sec GCD in Cataclysm, patch 4.0.1 (I believe), along with a mechanics overhaul (focus and stuff). Not that it matters when, it was long after TBC. Here have an old link that hopefully loads properly but I'll quote it here just in case:

"Ghostcrawler - Lead Systems Designer
Lowering the GCD is as close to anything on the never list. We will possibly do it for hunters, but that is because their resource system is going to prevent them from ever spamming multiple buttons at once (in the same way rogues have a lower GCD). Even with rage normalization there are going to be times when a warrior is at 100 rage and can unload with multiple attacks at once. The GCD is there for a reason, partially for game balance and partially to keep the server - client communication from getting gummed up."

"The way it is now

Currently hunters have a 1.5-second global cooldown. Our GCD is not affected by haste at all; unlike casters, our haste does not reduce our GCD, and of course those dirty rogues and feral druids just get a 1-second GCD automatically. This puts us among a very small group who is stuck at a 1.5-second GCD: death knights, warriors and hunters."

https://web.archive.org/web/20100609111538/http://www.wow.com/2010/06/07/scattered-shots-will-cataclysm-lower-our-global-cooldown/
All of that was posted Jun 7th 2010 at 5:00PM.
