### ISSUE TITLE
Magister's Terrace: Kael'Thas Sunstrider's bugged Flamestrike

### ISSUE THREAD

**Issue by Deadshade** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3694]
Kael's Flamestrike ability is bugged. It deals damage the second he casts it, then again (correctly) at the end of the 8 second duration. This makes the encounter entirely based on luck, as no-one can predict under whom he casts the spell.

Correctly he should cast the spell and the player should have time to move from the AoE zone before the damage at the end.

Spell ID=36731

Issue: Critical

**Comment by devidao** [comment]
Fixed

**Comment by devastator** [comment]
The fix is wrong. The spell itself is correct. The way it works is not.
How it should work: Kael Thas should use spell 36735, not spell 36731.
Spell 36735 spawns a trigger for the Flamestrike (Creature ID 21369). This creature should have aura 36730 and after 5 seconds of its spawn it should cast spell 36731 and despawn. Please refix. The Flamestrike Trigger AI can be made in the db, however the spell that Kael Thas uses should be checked and corrected in the script

**Comment by Nzzoth** [comment]
Fix denied on PTR.

**Comment by devidao** [comment]
Re-fixed according previuosly devastator comment

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by Nzzoth** [comment]
Fix confirmed on PTR.

**Comment by lajhar** [comment]
On live (15.4)
