### ISSUE TITLE
Windfury Weapon is not Scaling Properly with Attack Power

### ISSUE THREAD

**Issue by Applescruffs** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3730]
![wowscrnshot_121915_223908](https://cloud.githubusercontent.com/assets/16367408/11916375/2d89da02-a6a2-11e5-91b9-66f87859a8e0.jpg)

According to the tooltip, a windfury weapon proc should do more damage than the sum of two melee hits, due to the extra attack power. 
Testing in normal gear, an average windfury hit is less than 200% of a normal melee hit.
![wowscrnshot_121915_215315](https://cloud.githubusercontent.com/assets/16367408/11916367/e6b529ce-a6a1-11e5-9ee1-d818e5ca5d44.jpg)
Average melee hit = 390
![wowscrnshot_121915_215318](https://cloud.githubusercontent.com/assets/16367408/11916368/eab67a00-a6a1-11e5-9627-92bc81bc38b8.jpg)
Average windfury hit = 767
Gear stats:
![wowscrnshot_121915_223406](https://cloud.githubusercontent.com/assets/16367408/11916369/f9848518-a6a1-11e5-91bb-658d5c6cf18d.jpg)

767/2 = 383.5 average per swing. 

Wearing one piece + weapon, windfury is hitting on average for more than 200% of a normal melee hit.
![wowscrnshot_121915_223323](https://cloud.githubusercontent.com/assets/16367408/11916378/4f41cf92-a6a2-11e5-8f35-138419eac058.jpg)
Average melee hit = 235
![wowscrnshot_121915_223943](https://cloud.githubusercontent.com/assets/16367408/11916379/59f65cf0-a6a2-11e5-88c8-8e5e56e39ede.jpg)
Average windfury hit = 503
Gear Stats:
![wowscrnshot_121915_223335](https://cloud.githubusercontent.com/assets/16367408/11916380/614ab8c0-a6a2-11e5-8639-2a185a6ad981.jpg)

503/2 = 251.5 average per swing. 

This leads me to believe that the 475 attack power bonus in the windfury weapon proc is not interacting properly with the attack power provided by other gear and buffs.

**Comment by Applescruffs** [comment]
Patch 14.15.2 - Problem still exists 

With Windfury split up as two attacks again, the average windfury damage would still be higher than an average melee hit. 

![wowscrnshot_122615_170850](https://cloud.githubusercontent.com/assets/16367408/12008093/ac94493a-abf3-11e5-8dec-fd0b20c4fd03.jpg)

![wowscrnshot_122615_170854](https://cloud.githubusercontent.com/assets/16367408/12008097/c9a2196c-abf3-11e5-9ec3-3bc245b7b017.jpg)

Stats:
![wowscrnshot_122615_170856](https://cloud.githubusercontent.com/assets/16367408/12008098/ce80915c-abf3-11e5-8aaa-ebccc3943366.jpg)

**Comment by Delinquent1** [comment]
After this hotfix you made 1 windfury to appear as 2 different windfury attacks and being seperated into combat log events.

![](http://i.imgur.com/cSiDMtG.jpg?1)

It is 1 event with 2 procs. It shouldnt be split into two attacks in the combat log cause then it becomes again unrealistic and one cant track his damage properly.

**Comment by Delinquent1** [comment]
Mind adding a comment here saying you look in it or that you have no clue so we can help you?

**Comment by Urshark** [comment]
Hi guys,
I need to leave this comment here because my favorit wow class - spec was "killed". Why is the WF so reduced i realy don´t know.
Someone says it is "fixed" now! I´m sure, it is NOT.
WF was the strongest ability of enha shaman and it should be so. Enha is dead without it. If someone thinks it is too much, he is wrong and (I think) he never played enha - or he shouldn´t let him go too close to the target, that´s all. 
 
Now - WF is lower then normal melee hit and much lower as it should be - tried it in OG, on Feenix, Smoldeforge too, old Mystiq too...
http://s29.postimg.org/jrwd9q2mf/Wo_WScrn_Shot_011916_171400.jpg
http://s29.postimg.org/6qox8gzbb/Wo_WScrn_Shot_011916_171613.jpg
 
1h now - 
http://postimg.org/image/9g6ygwkjj/85f15a9e/      (non crit)
http://s28.postimg.org/v7crzxf19/Wo_WScrn_Shot_011916_174513.jpg     (crit)
 
result - wf dmg lower then melee hit
 
Wf crit is lower then melee crit? Players cried for many years ENHA SHAMAN IS OP, ENHA SHAMAN IS OP  PLEASE REDUCE HIS WF DMG... so here it is... enha shaman has nothing now, nothing. RIP
http://s10.postimg.org/7sbhczint/Wo_WScrn_Shot_011916_171436.jpg   ( s4 2h mace wep crit and  wf crit) this is sick, my s2 rogue deals equal dmg with 1h compared to this...
http://s24.postimg.org/mv7xbznet/Wo_WScrn_Shot_011916_171453.jpg   (wf crit... lower then the wep crit on the image before)
 
I though that i have WF rank 2 or 3 on the wep, but i dont.  :(
 
This is not normal -
on Mystiq (old czech/svk blizzlike server), Mysteria, Deffender, Hellground, Smoldeforge was the WF dmg Higher than wep dmg (and much higher if u were buffed, geared). 
 
Comparison
Smoldeforge -
http://s12.postimg.org/hmt2pjzq5/Wo_WScrn_Shot_011916_175234.jpg(non crit - WF dmg much higher than melee hit dmg)
http://s2.postimg.org/naf2mv1rt/Wo_WScrn_Shot_011916_175253.jpg(non crit comparison again)
http://s21.postimg.org/hh7o7pbzr/Wo_WScrn_Shot_011916_175205.jpg(crit WF much higher than melee hit crit)
 
 
Shaman fans dont give it up, report it, fight for it
 
or

save your Arena points and honor for something more useful. Enha is dead. 
If you expect big crits when buffed, if you expect big dmg when equipped, you will be very disappointed.  :(
 
Admins, please, repair Windfury in the shaman´s weapon if u can. Enha shaman is absolutely useless now. Many players play it, wanted to enjoy it. I know that many players cried because of big WF dmg before, but I think they were wrong. I played shaman for many years, on many servers (blizzlike servers, fun servers) and enha shaman SHOULD be a strong close target DPS. WF is what makes him strong (but WF is what makes him weak too because WF is accidental, you cannot decide when it procs - it can proc when you need it mostly or it don´t proc if u need it mostly, its simple).
 
Insomnia (mystiq comparison)
http://s16.postimg.org/3mg6mi1gl/Wo_WScrn_Shot_101312_111001.jpg(wf dmg much higher then melee hit...)
http://s12.postimg.org/fujm4pv31/Wo_WScrn_Shot_120712_171553.jpg
http://s23.postimg.org/5ye12cju3/Wo_WScrn_Shot_120712_171608.jpg (difference between melee crit and the WF crit)
http://s11.postimg.org/7vkof5lz7/Wo_WScrn_Shot_120712_171703.jpg  (difference between non crit melee hit vs. crit WF ) - big dif. yep, this is why enha rocks... but not now  :(      
http://s12.postimg.org/k6d9qu8bh/Wo_WScrn_Shot_070913_202143ssss.jpg  (849 is shock dmg... not wf... 907 weapon dmg / melee hit non crit and 1930 is non crit WF dmg)
 
and difference between melee and WF here (feenix)
http://s29.postimg.org/jrwd9q2mf/Wo_WScrn_Shot_011916_171400.jpg (really?  s4 2h wep...)
 
This makes no sense.
Please repair it if is it possible. :-/
I Appreciate your job you made here on this server, your time you spend here every day, I enjoy playing here and I hope many players enjoing it too. Hope you will not judge me, but this is not a good way to make this game funny (for many of us).

Thank you.

Best regards

Urshark

**Comment by Urshark** [comment]
Still no response. Windfury rank 5 is something like Windfury rank minus 3. Enha shaman is absolutely useles in Battlegrounds and pve. Don´t understand why noone cares about it. Many enha players are so bored of playing here now. Please write something, let us know, if somebody cares or not. This is realy annoying.

**Comment by Urshark** [comment]
Hi guys,

I know that we didn´t post here a video for you to imagine the problem of the reduced dmg of Windfury. But those screenshots we posted here  (and on the forum) are good/sufficient to imagine what´s the problem I think. 
http://www.wow-one.com/forum/topic/102739-where-is-my-wf-attack-power/
I know you have a lot of job here, so hope you are not bored of us. :)

**Comment by Urshark** [comment]
Hi again,

i made some test on training dummy in OG of WF proc and WF dmg again. So here are screenshots:

[url=http://postimg.org/image/rrgw3zw1d/][img]http://s24.postimg.org/rrgw3zw1d/Wo_WScrn_Shot_021516_140717.jpg[/img][/url]
[url=http://postimg.org/image/udoor2cch/][img]http://s16.postimg.org/udoor2cch/Wo_WScrn_Shot_021516_140743.jpg[/img][/url]
[url=http://postimg.org/image/sd9jh29yp/][img]http://s8.postimg.org/sd9jh29yp/Wo_WScrn_Shot_021516_140703.jpg[/img][/url]

U can see that the WF dmg is realy not working as it should - WF dmg should be higher then melee hit dmg. I had a WF rank 5 on the mace all the time. The chance of WF proc is ca. 19% (18,658%). So the chance to get the WF is lower too, but the main problem is the extremely low dmg it counts. 

Do you know about this fact or not? Will it be repaired or not? I don´t realy know what is the philosophy of this "fix" what was made on 26.december 2015, but the result of your fix is the enha is absolutely broken (useless) and players don´t play enha any more. It is 2 months for now... One more question, what´s the point of this reduced dmg of WF? I don´t understand. 

Thank you...

**Comment by Urshark** [comment]
Dear devs,

many players (enha shamans) have problem with realy low dmg of Windfury.
here is the relevant link to see how it should work -
http://vanilla-wow.wikia.com/wiki/Windfury_Weapon  
(windfury should cost no 7% of mana, but 178 mana). Read tips and read notes.

**Current situation:**
1) Windfury doesn´t make additional damage equal to two extra attacks **with X extra attack power**. The situation now is it makes a ca. half dmg.
http://s29.postimg.org/jrwd9q2mf/Wo_WScrn_Shot_011916_171400.jpg
http://s29.postimg.org/6qox8gzbb/Wo_WScrn_Shot_011916_171613.jpg
Windfury attacks are lower then normal melee hit dmg. They absolutely ignore bonus attack power (475 bonus AP).

2) The proc chance is ca. **18-19%.** 
http://s12.postimg.org/6b2o0hb0t/Wo_WScrn_Shot_021516_140743.jpg
178:2= 89 Windfury procs (Recount addon counts 1 Windfury as 2 attacks)
477 is the count of normal melee hits.
So 477:100= 4,77
89:4,77= 18,658%

3) Windfury doesn´t offer **up to 40%** damage increase to a shaman's base melee DPS (if wielding a single three second or slower weapon). It makes half dmg.
[url=http://postimg.org/image/ba9fp7cp7/][img]http://s9.postimg.org/ba9fp7cp7/Image00001.jpg[/img][/url]
On the second screeshot you can see how low is the dmg of Windfury (my shocks made bigger dmg). Here I tried the classic pve rotation with one-hands, popped trinkets on CD, shocks on CD, stormstrikes on CD. Windfury is realy low.
[url=http://postimg.org/image/z0ij1t5iv/][img]http://s15.postimg.org/z0ij1t5iv/Image00002.jpg[/img][/url]

**How it should be:**
See the link -
http://vanilla-wow.wikia.com/wiki/Windfury_Weapon

1) Each hit has a 20% chance of dealing additional damage equal to two extra attacks with X extra attack power. Lasts 30 minutes. In TBC is it 475 extra attack power. 

2) The proc chance should **be 20%**. Not 19%,18% or lower.

3) Windfury is the main enhancement shaman buff. It offers up to 40% damage increase to a shaman's base melee DPS (if wielding a single three second or slower weapon), not counting the attack power bonus granted on 2/7ths of all swings. 

In Pre-TBC, a lucky shaman was able to one-shot Clothies with slow two-handed weapon if Windfury proc'd.


It is 2 months now without any response, any answer and many players are frustrated because of it.
Please take a look on it.
Thank you for taking care and kind regards,

**Comment by Zerixx** [comment]
To whomever sees this, answer me the following: in full bis gear, what should the average hit damage be? I've tinkered with it and it's not ~390 anymore, it's closer to 500 but I never played shammy in tbc, maybe someone else could tell me what kind of numbers we're looking for.

Thanks!

**Comment by Delinquent1** [comment]
The WF imbue rank 5 in complete bis gear unbuffed should be approx:
Main hand wf:
1200-1400 non crit 2400-2900 crit (1 hit & no armor mitigation)
2300-2800 non crit 4800-5800 crit (2 hit & no armor mitigation)

740-880 non crit 1500-1800 crit (1 hit & with armor mitigation)
1400-1700 non crit 3000-3600 (2 hit & with armor mitigation)

For the offhand the damage is reduced 50% >BEFORE< all attack power increase buffs

Further calculations can be found here (check bottom tabs)
https://docs.google.com/spreadsheets/d/1k3xYw4JtqLPzndLRhwzXq5w83h7uYWzgNLBIVdB_12I/edit#gid=0

**Comment by Zerixx** [comment]
Yeah. That's the result I ended up with. Gonna tweaj it out tomorrow and be done with it I think. See my thread on the forums for updated screenies and lmk what you think!

**Comment by Applescruffs** [comment]
Fixed.
