### ISSUE TITLE
[rogue] Poison benefit from spell damage

### ISSUE THREAD

**Issue by Lederi** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3753]
## How it is

Poisons from a rogue benefit from + spell damge. This poisons are all ranks of 
- Wound Poison [V](https://www.wow-one.com/database/index.php?spell=27283)
- Instant Poison [IV](https://www.wow-one.com/database/index.php?spell=11341)
- Deadly Poison [VII](https://www.wow-one.com/database/index.php?spell=27282) 
## How it should be
- Poisons should only benefit from buffs wit X% more spell damage like [Misery](https://www.wow-one.com/database/index.php?spell=33195).
- Poisons should **not** benefit from spell damage from gear or buffs like [Wrath of Air Totem](https://www.wow-one.com/database/index.php?spell=3738).

**Comment by devastator** [comment]
Fixed. Soon on PTR

**Comment by Jackx666** [comment]
"Fixed"? Are you guys completely ignorant?
"Patch 3.0.2 (2008-10-14): Damaging poisons now scale with attack power."
It did SCALE with spell damage till this patch...

**Comment by Lederi** [comment]
It is wrong to deduce the statement "SCALE with spell damage" from "Patch 3.0.2 (2008-10-14): Damaging poisons now scale with attack power.".

Please present facts of your statement.

**Comment by Jackx666** [comment]
Well your original statement is wrong too, since there are no proofs that it doesnt scale. We all heard about "spell rogues, fire rogues" since vanilla, and you cant find any mention about scaling removal in any of patch notes.
Despite all this, its viable only in pve, it hurts nobody, its very balanced and regular rogue is still far superior.

**Comment by Lederi** [comment]
> Well your original statement is wrong too, since there are no proofs that it doesnt scale.

### Proof 
There are  no sources about the scaling from spell damage on poisons on retail, neither on wowwiki nor wowhead. If it should scale, then would somewhere a forums entry found. But nowhere a texts or a videos exist that demonstrate the scaling.
Therefore, we can assume the poisons did not benefit from spell damage.

> We all heard about "spell rogues, fire rogues" since vanilla,...

All what i found or heard was from private server projects, nothing from retail.

**Comment by Jackx666** [comment]
There is no clear denial of it either. 

>  Proof
> 
> There are no sources about the scaling from spell damage on poisons on retail, neither on wowwiki nor wowhead. If it should scale, then would somewhere a forums entry found. But nowhere a texts or a videos exist that demonstrate the scaling.
> Therefore, we can assume the poisons did not benefit from spell damage.

By no means this is a solid proof...
Spell rogue is a very rare thing and it was a long time ago... 99% sources of tbc guides/info/forums are dead.

And again, since its not hurting anyone, actual status is unclear and probably never will be, what is the point of investing your time and "fixing" it this way?

**Comment by Fleischi** [comment]
It is and was very rare that player stats get added to an effect of an item. It is close to impossible that something like that was the case without anybody in the usual places mentioning it.
There is not even so much as a tiny little hint for anything at all being added to these poisons.

Add to that the fact that private servers are known to have this issue of adding spell damage or AP where they dont belong. This is just because they are the default values on newly created items with spells. The person (or automated script) that added them did not set the right values.

So I would suggest that you back up your claim that there should be added spell damage with a source. The usual places to look for exactly that are silent about an oddity like that. I see the burden of proof on your side, @Jackx666 .

PS: 'the point of investing your time and "fixing" it' is to get things closer to the original experience. There are enough servers with random things happening. This one trys to be blizzlike. So we try to help a little when we can. If you want random things to happen then this might not be the right place to look for them.

**Comment by Daweedian** [comment]
Well, lets look at it from this perspective. You can reach 2k dps with blue/green gear fully buffed with like 1k spell power and 3 weapons on switch. I have spell gear like that and I tested it. So, it would be more than viable on retail for every rogue to go as spell rogue since you could gear up for t6 raiding in less than 2 weeks. Do few heroics, even normals, several quests, craft some items and you are good to go. So, question is, why haven't I see a single spell power rogue on retail on medium populated realm? Answer: It didn't work like it works here. Rogue from guild is doing 3.5k dps on target dummy and just a bit less dps on most of the static bosses.

**Comment by Nzzoth** [comment]
There is more than 10 arguments that I could give you why this is wrong. However I would enter some topics I shouldn't. I'll just leave it at this. If it scaled with SP it wouldn't scale at the rate it did prior to this fix.

**Comment by repae1f** [comment]
[quote]Spell damage doesn't affect poisons, nature damage does (as Barva stated). However it is never beneficial to equip nature damage gear for this purpose.[/quote]
http://www.wowhead.com/forums&topic=16706/super-poisons

**Comment by Daweedian** [comment]
@repae1f 

Thank you, this is all that's needed for fixing this. If you go ful nature damage gear you will have 5k HP in the raids and not be able to survive, not to mention that you CAN'T get same amount of nature damage as amount of spell damage.

**Comment by lajhar** [comment]
On live (15.3)
