### ISSUE TITLE
Restoration Shaman 4 piece t6 (5% increased chain heal) does not work

### ISSUE THREAD

**Issue by blackhodown** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3780]
It has been submitted before without evidence and you tested it and said it was working.

It is not working.

Here is an imgur album with proof: 
[Shaman](http://imgur.com/a/r7hb8)

**Comment by blackhodown** [comment]
Those are all rank 5 chain heals, spellpower basically the same. The difference in average hit should be upwards of 150 healing, but as you can see there is almost no difference.

**Comment by Nzzoth** [comment]
30 samples is not evidence. You can claim that orcs racial Hardiness is bugged because you got stunned 25 out of 50 times which makes it 50%. However lets get to evidence.

In this screenshot you can see my bonus healing and set pieces:
http://prntscr.com/aidufw
Chain heal rank that was used is rank 1 which has a difference of 48 healing between maximum and minimum (Conviniently I could get both values in 1 screenshot)

Now in the second screenshot few casts in you can already see the difference:
http://prntscr.com/aidv49

Issue closed set bonus is working as intended.
