### ISSUE TITLE
warriors don't get rage from received damage when attack partially blocked

### ISSUE THREAD

**Issue by repae1f** [FeenixServerProject/Archangel_2.4.3_Bugtracker#3876]
https://youtu.be/RYqkuTfx7OY

on video when attack block gains only 1 rage point from this talent https://www.wow-one.com/database/?spell=12727

https://web.archive.org/web/20080624041006/http://forums.wow-europe.com/thread.html?topicId=83678537&sid=1&pageNo=1#16

**Comment by Daweedian** [comment]
Last night on Mother our dudu tank had horrible port and he died and warr tank managed to pick her up. The whole fight he had 0 rage. He couldn't do a thing. We had to wait for 15 seconds so he could pop battle shout. I understand that rage wasn't scaling properly before but it certainly doesn't scale properly now. We needed for him to get hit in order to get rage because he gained none from hitting. I will see if we have it recorded and I will post it as soon as I can.

**Comment by Qingle** [comment]
Tested the rage generation in a Heroic instance last night, rage generation is massively undertuned.

http://wowwiki.wikia.com/wiki/Rage - Scroll to Formulae, Rage Conversion Rate is further down.

This page gives you a good representation of the amount of rage that should be generated not only on hit, but when you are hit. Note: This page also includes the rage conversion formula.

This issue should a huge priority as Warriors and Druids currently have no resources to generate threat, which essentially makes them useless tanks.

**Comment by Donlund** [comment]
I apologize if this "bumping" is not allowed, I am adding nothing new except underlining the point of what OP is repoting. I am just getting a little worried about the lack of reply to this issue, so I am politely directing your attention here in case you missed it.

I hope anyone with the power to investigae and fix this realize how severe this particular bug is for warrior tanking. With the recent fix so that warriors no longer incorrectly gain rage from dodge/parry warrior tanks are back to relying on generating most of their rage from actual dmg taken, as it should be. 

The whole role of the protection warrior is however build up around using shield block ability to be able to block any attacks that are not avoided, mitigating some of the dmg taken and making it (in most scenarios) impossible to receive a crushing blow. A full t6 geared prot warrior has maybe 6-700 block value, meaning that on most high end raid encounters you will still take alot of dmg on each hit that is not avoided, even when blocking the attack. With this reported bug, you do not receive any rage at all from the dmg that was not blocked, you hereby loose a major source of rage generation. 

This bug makes the utility of a warrior tank much, much lower than what I assume was intended when fixing the incorrectly gained rage from dodged/parried attacks.

Thank you for reading and considering adressing this swifty :)

**Comment by repae1f** [comment]
fixed on live
